---
- name: Install required packages
  become: yes
  apt:
    pkg: "{{ packages }}"
    state: present

- name: "Do apt {{ apt_upgrade }} upgrade"
  become: yes
  apt:
    update_cache: yes
    upgrade: "{{ apt_upgrade }}"
